import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import './globals.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
        </head>
        <body className="bg-gray-900 min-h-screen">
        <Navbar />

        {children}
        <Footer />

        </body>
        </html>
    );
}
