import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import './globals.css';

export const metadata = {
    title: 'Lucius Aeby',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
            <link rel="icon" href="/favicon-16x16.png" sizes="16x16" />
            <link rel="icon" href="/favicon-32x32.png" sizes="32x32" />
        </head>
        <body className="bg-black min-h-screen">
        <Navbar />

        {children}
        <Footer />

        </body>
        </html>
    );
}
